---
title: "ZOOL4000 Unessay Project"
output: html_document
date: "2025-04-23"
---    
Created by: Winnie Allred    
```{r, echo = FALSE}
library(qrcode)
qr <- qr_code("winnie-weidow.github.io/ZOOL-Project")
plot(qr)
```    

## Elephant Seal Battles: Mating Ground or Burial Ground?    
An interactive story-based game.    
    
## Points:     
Points are based on 4 categories: dominance, reproductive success, health, and social bonding.    
Start with:    
•	0 points – dominance    
•	0 points – reproductive success    
•	5 points – health    
•	0 points – social bonding    
Keep track of points through the game by adding or subtracting them as each scene concludes.    
    
## Game Play:    
One person narrates and the other makes decisions at each choice point. Keep track of your points and calculate your total success score at the end of the game by adding the final scores from each category.    
    
## Scene 1: Arrival at the Breeding Grounds    
    
Setting:     
You are playing the role of a young male elephant seal that is arriving at the breeding grounds for the first time. The objective is to choose the strategy that will create the best balance between costs and benefits. Older, more experienced males are already present and dominating the breeding grounds. Direct competition against the largest males could lead to failure in reproductive attempts, so which strategy will you choose to pass on your genes and survive this brutal environment?
    
    
Narration:     
As you arrive at the beach, you see the dominant males already actively displaying and establishing their control over the harems of females. What’s happening to the losers? They are on the sidelines. Now it’s time to make some choices. Where will you end up?
Your goal: maximizing your reproductive success while minimizing damage to your health. 
    
    
Choice Point: time to make some decisions.    
A.	Avoid direct contact with the largest males. Instead, challenge a medium bull for control over his harem. High risk, high reward. This may result in gaining your own territory, or you could risk being dominated.    
B.	Try to sneak a copulation without attracting the attention of the dominant male. This strategy has a low chance of success, but it is less risky than direct competition with the other males.    
C.	Flirt with the females that are more distanced from the harems. Try to be noticed by females. This is time-consuming and may result in delayed benefits. However, it is low risk.    
    
    
Outcomes:     
If you chose:     
A.	You challenge a medium sized bull, and he overpowers you. You are injured, but you also gain some respect for your efforts. +1 dominance, -2 health.    
B.	As a dominant bull chases off a rival, you sneak in and copulate with a female near the edge of the harem. You are then noticed and chased away. +1 reproductive success, -1 health.    
C.	You spend the day near a smaller group of females, subtly displaying, and one of them notices you. No mating today. +1 social bonding.    
    
    
## Embedded concepts:     
•	intrasexual selection: adaptations related to direct competition, typically between males    
•	alternative mating strategies: sneaky tactics when you can’t dominate    
•	intersexual selection: adaptations appealing to female choice through indirect competition    
•	resource defense polygyny hypothesis: the males guard the resources (in this case, space on the beach) and attract females. They protect the resources and females by establishing a territory.
    
    
## Scene 2: Rising Tension    
    
    
Narration:     
The next day arrives, and you are still flippin’. Tension rises on the breeding grounds as confrontation becomes more frequent. Every move you make is vital to your survival and success.    
    
    
If you chose A: direct competition, lost, and was injured…    
The males know to keep an eye on you, and you have made an impression on the females. A particular female is very taken with you. She subtly separates herself from the dominant male’s harem, making her way towards you.    
    
    
Choice point:    
A1. You let her approach you, cautious of the nearby dominant bull. This subtle tactic may help you avoid another fight.    
A2. One female is not enough. You bellow to attract more. It is very bold of you, and could increase your dominance status. However, there is risk of injury.    
    
    
If you chose B: tried to sneak a copulation…    
You are injured at the sidelines, but you’re not the only one. Another male is laying low and shares your objectives. Can you work together?    
    
Choice point:    
B1. Work cooperatively with the other male. The other male distracts the dominant male so you can sneak in a copulation or two. You take turns, reciprocating the sacrifice so the other male can also benefit.    
B2. Forget the other guy. Try again by yourself, but refine your strategy - better timing, quicker retreat. The payoff may be higher than it would be if you cooperated with another male as the distraction tactic could result in fitness costs.    
    
    
If you chose C: focused on drawing the attention of females…    
You were noticed by a female earlier and she is now being pursued by another male. She doesn’t seem very interested in him.     
    
Choice point:    
C1. You intervene and chase off the other male, which may strengthen your social bond with the female or scare her away.    
C2. Let the female choose while you observe the new interaction. By not intervening, she may be more impressed by your patience. This may result in delayed gratification.    
    
    
Outcomes:     
If you chose…    
A1. Aware of the close-by dominant male, you cautiously mirror the movements of the female. She does not back off. While the dominant bull is distracted, you experience reproductive success. +1 reproductive success, +1 social bonding, -1 health (due to stress).    
A2. You let out a mighty bellow. Oh, the females notice you, but so do your many rivals. One of them charges at you. You escape, but with many new injuries. However, every male and female on the grounds knows who you are. +1 dominance, -2 health.    
B1. You and the other male work cooperatively. While one of you distracts the dominant male of the harem, the other sneaks in. The other bulls eventually catch on, but over the next several days, you both experience reproductive success. +2 reproductive success, +1 social bonding, -1 dominance (you sneaky son of a gun).    
B2. You refine your strategies. You move to a larger harem where there are way more females than the dominant male can constantly keep his eye on. As the male gets distracted with some females on the far side of the harem, you sneak around the other side and interact with a female that was left exposed.  Afterwards, you quickly retreat. +1 reproductive success, -1 health (due to exhaustion), -1 dominance.    
C1. You put yourself between the female and the other male. You are slightly bigger than the other male, and he doesn’t think it’s worth the energy to fight with you. Mating doesn’t happen now, but you have strengthened your bond with the female. +2 social bonding, +1 dominance.    
C2. While the female does interact with the other male, she is not interested in him. She retreats from him, but closer to you because she is more comfortable when you’re around. +1 social bonding.    
    
## Embedded concepts:     
•	cooperation through mutualism    
•	delayed reciprocity    
•	female choice    
•	direct and indirect benefits    
•	social bonding    
•	bold courtship displays    
•	greenbeard allele hypothesis: likeminded phenotypes will converge and interact    
    
    
## Scene 3: Arrival of a New Challenger    
    
    
Narration:     
You’re nearing the end. The breeding grounds have been crazy and intense for days, and the chaos only increases as time goes by. You may be feeling stronger or feeling the intensity of your wounds, depending on your past choices. You have made a name for yourself: bold, sneaky, or impressive…     
All of that seems forgotten as everyone witnesses the arrival of an older, massive, confident bull. The dynamics on the playing field are about to change. How are you going to adjust your strategies during the new power struggle?    
    
Summary: If you chose…    
Path A, bold in combat: you and the other young males might consider taking advantage of the exhaustion that results during the impending battles.    
Path B, sneaky and clever: the upcoming confusion might be the perfect cover you need to continue with this tactic, or it could prove to be deadly.     
Path C, impressive to the females: as the structure of the harems is disrupted, females may assemble around you, as you have worked so hard to establish social bonds with them. This could be where your efforts to create social bonds pay off.    

    
Choice point:     
A.	Try to overpower a dominant male. The dominant males are getting exhausted. You and the other males don’t intentionally work together, but you all start pushing the boundaries at the edges of the harems. The dominant male’s ability to fend all of you off may be waning.     
B.	You try the sneaky strategy and take advantage of the time the huge bulls are distracted fighting. This is very risky, but it could lead to success again.    
C.	Remain close to the females that are gathering around you. If the social bonds you have been cultivating are strong enough, this may be the opportunity you have been waiting for.    

    
Outcomes:    
If you chose:    
A.	You charge at the dominant male and, coincidentally, so do many other young males. The alpha is exhausted, and he is successfully driven away. Now who gets to be in charge of the harem? You successfully drive back some of your new rivals. There’s no saying how long they will stay away, but you’re in charge… for now. +2 dominance, +1 reproductive success, -2 health.    
B.	You sneak around and manage a copulation with a female, but you are also seen by another male. He charges at you, but you retreat and barely escape. +1 reproductive success, -1 health.    
C.	There is fighting going on everywhere, but the females gathered around you stay close until things start to calm down. Some of the females join the new alpha, but some of them stay with you, giving you a brief, uninterrupted time interval with some females. +2 reproductive success, +2 social bonding.    
    
    
## Embedded concepts:     
•	dominance hierarchy      
•	by-product collaboration (in contrast to cooperation)       
    
